# Generated by Django 3.2.6 on 2022-01-26 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='edit_questionanswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
                ('question_en', models.CharField(max_length=1000)),
                ('answer_en', models.CharField(max_length=1000)),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2022, 1, 26, 15, 7))),
                ('updated_time', models.DateTimeField(default=datetime.datetime(2022, 1, 26, 15, 7))),
            ],
            options={
                'db_table': 'questionanswer',
                'ordering': ('id',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('created_by', models.CharField(max_length=1000)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2022, 1, 26, 15, 7))),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 1, 26, 15, 7))),
                ('updated_by', models.CharField(max_length=1000)),
                ('updated_time', models.DateTimeField(default=datetime.datetime(2022, 1, 26, 15, 7))),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2022, 1, 26, 15, 7))),
                ('deleted_by', models.CharField(max_length=1000)),
                ('deleted_date', models.DateTimeField(default=datetime.datetime(2022, 1, 26, 15, 7))),
                ('deleted_time', models.DateTimeField(default=datetime.datetime(2022, 1, 26, 15, 7))),
                ('status', models.BooleanField()),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('last_login', models.DateTimeField(default=datetime.datetime(2022, 1, 26, 15, 7))),
                ('path_profile_pic', models.CharField(max_length=1000)),
                ('role_code', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
                'ordering': ('id',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='questionanswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
                ('question_en', models.CharField(max_length=1000)),
                ('answer_en', models.CharField(max_length=1000)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2022, 1, 26, 15, 7))),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 1, 26, 15, 7))),
                ('user_id', models.IntegerField()),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2022, 1, 26, 15, 7))),
                ('updated_time', models.DateTimeField(default=datetime.datetime(2022, 1, 26, 15, 7))),
                ('updated_by', models.CharField(max_length=1000)),
                ('status', models.BooleanField()),
                ('view_count', models.IntegerField()),
                ('department_id', models.IntegerField()),
            ],
            options={
                'db_table': 'questionanswer',
                'ordering': ('id',),
            },
        ),
    ]
