# Generated by Django 3.2.6 on 2022-01-27 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220126_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 15, 5, 9)),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 15, 5, 9)),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 15, 5, 9)),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='updated_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 15, 5, 9)),
        ),
    ]
